export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Footer } from './Footer'
export { default as ControlPanel } from './ControlPanel'
export { default as Icon } from './Icon'
export { default as Input } from './Input'
export { default as Button } from './Button'
export { default as H2} from './H2'
export { default as UserInfo } from './UserInfo'
export { default as UsersContent } from './UsersContent'
export { default as PostContent } from './PostContent'
export { default as Comments } from './Comments' 

